FROM chromadb/chroma:0.5.23

USER 0

RUN chgrp -R 0 /chroma && \
    chmod -R g=u /chroma && \
    mkdir -p /chroma/chroma && \
    chgrp -R 0 /chroma/chroma && \
    chmod -R g=u /chroma/chroma

RUN CHROMA_PKG=$(python -c "import chromadb; import os; print(os.path.dirname(chromadb.__file__))") && \
    chgrp -R 0 "$CHROMA_PKG" && \
    chmod -R g=u "$CHROMA_PKG"

USER 1000
