apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: evil-ai-papers-pvc
  labels:
    app: evil-ai-rag
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: evil-ai-chromadb-pvc
  labels:
    app: evil-ai-rag
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
